global using CommonBasicLibraries.AdvancedGeneralFunctionsAndProcesses.BasicExtensions;
global using CommonBasicLibraries.AdvancedGeneralFunctionsAndProcesses.FileFunctions;
global using CommonBasicLibraries.AdvancedGeneralFunctionsAndProcesses.Misc;
global using CommonBasicLibraries.BasicDataSettingsAndProcesses;
global using CommonBasicLibraries.CollectionClasses;
global using SvgHelper.Blazor.Logic.Classes;
global using SvgHelper.Blazor.Logic.Classes.Interfaces;
global using SvgHelper.Blazor.Logic.Classes.SubClasses;
global using System.Drawing;
global using cc = CommonBasicLibraries.BasicDataSettingsAndProcesses.SColorString;
global using Microsoft.AspNetCore.Components;
global using Microsoft.AspNetCore.Components.Rendering;
global using Microsoft.AspNetCore.Components.Web;